import java.util.ArrayList;

/** Course.java
* Provides a uniform structure for providing course information to UI elements.
* Course classes are generated by the University Classes
*
* @version 1
* @ date 12/08/17
**/
public class Course {

    /** Title of the course */
    private String title;

    /** Description of the course */
    private String description;

    /** URL for the provider's cost information */
    private String cost;

    /** Keywords about the course, pulled from the website */
    private ArrayList<String> keywords;

    /** Accessors and Mutators */

    public String getTitle() {return title;}

    public String getDescription() {return description;}

    public String getCost() {return cost;}

    public ArrayList<String> getKeywords() {return keywords;}

    public void setTitle(String title) {this.title = title;}

    public void setDescription(String desc) {this.description = desc;}

    public void setCost(String cost) {this.cost = cost;}

    public void setKeywords(ArrayList<String> keywords) {this.keywords = keywords;}

    public void addKeyword(String word) {keywords.add(word);}

}